### ISSUE TITLE
Should I have used ->nullable()?

### ISSUE THREAD

**Issue by ctrlcctrlv** [infinity-next/infinity-next#128]
https://github.com/infinity-next/infinity-next/commit/4af5ac187e02559f010ceedbfac6813411577acc

I think I made a mistake with this commit. Pls advice Josh

**Comment by jaw-sh** [comment]
Huh? Did each of these tables really cause problems?

`Schema::table('bans', function(Blueprint $table)` is scary because those columns should NEVER be null or anything but IPs.

`Schema::table('posts', function(Blueprint $table)` is scary because it ''already'' is nullable. It should probably default(NULL) instead.

`Schema::table('reports', function(Blueprint $table)` should be the same as posts.

Why was SQLite throwing issues?

**Comment by ctrlcctrlv** [comment]
I don't know for sure. Please try yourself. Revert 4af5ac1 and then try to `artisan migrate` with a clean SQLite DB. It doesn't work and throws multiple `Cannot add a NOT NULL column with default value NULL`. I had to patch each table it was complaining about.

**Comment by jaw-sh** [comment]
http://stackoverflow.com/a/6710280/4635062

This is an issue with SQLite. Apparently it doesn't complain when you're creating the table, only when adding them, even if there is no data in the table.

**Comment by ctrlcctrlv** [comment]
So, that's interesting info - but I'm not really sure how to react to it. It's damn convenient to be able to use SQLite, and reverting 4af5ac1 and thereby making SQLite unusable would suck. SQLite is literally plug and play provided you have pdo_sqlite.so and libsqlite (which almost every Linux computer does)...

But then again, this kind of ruins some DB integrity... :frowning:

**Comment by jaw-sh** [comment]
What we're going to have to do is, when we consolidate the migrations into a single file for installation, is remember to remove these defaults because it should then work for SQLite.

**Comment by rajlaksh** [comment]
->nullable is good for Eloquent Relationship.

Laravel eloquent need ->nullable column for relationship. 

example
Post::with('user');

that will look column name user_id in Posts table and it will work only if user_id column is nullable because Users Table id column is nullable. you need to match column for eloquent relationship :smile:

**Comment by jaw-sh** [comment]
Closing. When we merge migrations into one creation script we'll fix this.
