### ISSUE TITLE
Future of Infinity Next...?

### ISSUE THREAD

**Issue by milezteg** [infinity-next/infinity-next#245]
I've been following this project closely since mid 2015 and was sadface.jpg to see it implode this year.  I've worked more than most with the codebase and found it to be pretty good overall, but as with most PHP applications, it suffers from high CPU usage when under load.  I know this because I'm one of the few people who actually bothered load testing it, and had been suggesting others do so as far back as Oct 2015.

That said, I'd honestly hate to see all this good work go to the dust bin.  I think Josh did a lot of innovative things with Next and it deserves to live on in some form.  Like him or hate him, he was dedicated to the project and other than being an asshole occasionally and calling Freddy a hobgoblin, he seemed to really want this to succeed.

**We ran some tests again last night in #8chan-dev and came away with the same conclusions:**

- 8 cores/4GB - freeBSD + pgsql + php7-fpm + redis w/ 8 php-fpm workers:  http://pastebin.com/hk7eQRPm 

- `OdiliTime: The memory footprint is acceptable at around 50mb / worker.  Next handles the DB side well but the fragment caching is where it fails.`

- We maxxed out at 10 request per second per core.  We need to hit around 25 r/s.  We tried to pull the latest commits that fix the captcha issue but composer update breaks (again).  We'd love to run these tests with Josh's latest code and his chosen platform (come find milez or odilitime in #8chan-dev Josh or we can do it privately).

- It seems obvious Next needs another cache layer aside from the current Laravel cache.  I think this would save Next.  Josh seemed to implement Varnish on *some* parts of Next but this seems to have been scrapped...?

- The community and donators deserves some type of update on where this software is going.

- MIT license or GTFO.

**Comment by jaw-sh** [comment]
The license will not be changed and everything else takes a back seat.
Fredrick has stopped trying to get 8chan to work with Next because he
knows, and has publicly admitted numerous times, that the copyright is
mine. Jim refuses to work with the code unless it's GPL, which would
allow him to use proprietary copies for 8chan. His original offer in
November would have involved purchasing and closing the source entirely,
in exchange for paying me 100k PHP a month as a full time employee. I
refused, because I had promised the source would be opened. After my
refusal, Jim cut all contact since. On the week the project dropped by
Fredrick, he made a new offer of $100/one time and tried to blackmail
me into releasing the source to him or offering RQi a sublicense.

Preserving the freedoms of 8chan's users is my primary concern, and to
do that I have to prevent Fredrick and Jim from stealing the source and
doing with it as they please. If Fredrick wanted to run a copy of Next,
technical issues aside, he would be allowed to, but Jim's either
delusional and paranoid regarding what legal actions I would take with
the source code, or he knows he wants to violate the license. I am a
23 year old nerd without the money or influence to launch frivolous
cases, but what cases aren't frivolous are those backed by the lawyers
of the Free Software Foundation and Richard Stallman.

IF

1. The source was his, or
2. He did not intend to violate my FSF protected license,

There would nothing to worry about regarding using it. Since they do not
plan on using Next, I can assume that they both understand that the
IP controller is me and that they would violate the AGPL stipulations
and/or put code into the codebase that they would not want public. Next
can work and Fredrick knows this, which is why he is still
fabricating claims and trying to push me around both in public and in
private.

The most hilarious and ironic part of all this is that, if he had just
offered me the 10 BTC he had in savings for a sublicense, I would have
agreed to it. Instead, he burned bridges, attacked me, and constantly
tried to strip me of my property rights through extrajudicial means. As
a result, I may never do business with Fredrick or RQi and they may
either oblige the conditions of my public AGPL license or they can find
an alternative. If they do choose to use the code, I will enforce my
licensing.


Your contributions and technical analysis of the existing code is great
and I will apply it to development if and when development continues, 
but
the chances of 8chan ever using it because of how Fredrick handled the
severing of ties are next to none. He has successfully sabotaged a 
year's
worth of work for his website and is on a crusade to steal from me now
that he's (probably) in hot water with Jim. Everything he has is 
contingent
on Jim continuing to like him, and I do not want to take that from him,
and I understand why he is doing this (to save his own skin), but at the
same time I cannot tolerate it and will explain in thorough detail the
demise of Infinity Next this weekend when I do my stream.

**Comment by interjection** [comment]
>I will enforce my licensing.
I don't understand this bit. Is it implying that the act of having a users browser fetch from their softserve endpoint, which is proprietary on the backend, constitutes a violation of the AGPL? Or just that you will want their changes to the codebase itself public?
It shouldn't be too hard to build an abstraction for advertisements so admins wouldn't even have to modify widgets/ads/* and you could even have multiple ad provider options, all of this stored in the database and cached of course. Perhaps I don't really understand what they're worried about.

You are right to be pissed off about the burnt bridge. But, on the other hand, the application is a bit hard to cache with the choices made and Laravel's sessions. The simplest way forward I see is caching anonymous and forcing mods over an additional /cp/ endpoint, no?

**Comment by odilitime** [comment]
@milezteg brought up the future of next, and @jaw-sh you focused on 8chan. Are you saying there is no future of Next without 8ch? Because there are plenty of other chans interested in the software. Let's please focus on the technical issues and keep the drama of the past out of this.

**Comment by interjection** [comment]
@odilitime https://github.com/HaiFangHui/sessionmonster looks promising as well, although it might need updated for Laravel 5

**Comment by jaw-sh** [comment]
Okay. It's time to keep going.
@interjection I'm interested in seeing your work. Keep in touch mate.
