### ISSUE TITLE
I believe that one can in fact sell AGPL code.

### ISSUE THREAD

**Issue by iyra** [infinity-next/infinity-next#289]
Your readme states:

> You will not sell copies or modifications of this source code (no sublicensing).

However selling copies or modifications of the code is allowed under the AGPL. I'm pretty sure that sublicensing isn't allowed, but selling the code is. Selling binaries is also allowed so long as you provide the source.

Am I interpreting the statement wrong, or is my analysis of the AGPL wrong? Please help me clear up the confusion.

**Comment by jaw-sh** [comment]
You have to always provide the source code with any living instance of
the software, and any modifications of the source code most also be
AGPL. I don't know if selling the code is specifically prohibited, but
you'd either have to not run the software yourself publicly to keep it
closed source, or you'd have to find a way to charge money for code that
is freely available. I don't know if that's what you're asking; that
sort of situation seems rather nightmarish.

Profiting from the code is 100% OK (i.e. running ads, modifying it to
have premium services, etc).

**Comment by projectilemotion** [comment]
>or you'd have to find a way to charge money for code that is freely available

This is allowed under the (A)GPL; it's not disallowed in any of the GNU licenses. It's just a little confusing when in the Readme it says that you can't sell copies of the source/binaries with source, but the AGPL allows you to do it. It might be seen as saying "this software is licensed under the AGPL, but you're not allowed to sell it", which I don't think is your intention here.

https://www.gnu.org/philosophy/selling.html

**Comment by jaw-sh** [comment]
Your idea for how selling copies of the software would work sounds
incredibly intellectually dishonest. It's like charging $50 for software
and then saying you just paid for the disc and delivery. I guess it's
permissible but it's scummy as all fuck. Is that what you're asking?
Because this sounds incredibly pedantic. It _EFFECTIVELY_ prevents you
from selling the code because there's nothing stopping people from
downloading it if the license is obeyed.

**Comment by zero17333** [comment]
"It _EFFECTIVELY_ prevents you from selling the code because there's nothing stopping people from downloading it if the license is obeyed."

I think selling the source code is a way to work donations into your code.

What I mean by this is people can download the code freely but they can also buy the software where they will get the software and you will get donations from them.

Also if this was some phone game or something selling the software would make more sense as most of the people buying the game wouldn't have a clue as to how they would compile the game. Really,  buying a copy of the code would be out of convenience and an easy way to get money. 

If you are concerned about intellectually dishonesty it might be a good idea to say that this code is free software but that people may choose to donate through buying it.
