### ISSUE TITLE
Ability for BOs to sort stickied threads?

### ISSUE THREAD

**Issue by Gooberpatrol66** [infinity-next/infinity-next#293]
There doesn't seem to be a way to order the position of stickied threads. As a BO it's quite annoying.

**Comment by GarbageHamburger** [comment]
https://github.com/infinity-next/infinity-next/blob/master/app/Board.php#L1180
This proably should've been `'stickied_at'` instead of `'stickied'`, which would make it so that the newest stickied thread would stay at the top. Should be a simple enough fix. I don't have any computer that I can use as a testbed for Infinity Next at the moment, but if Null doesn't mind I can send in a PR that fixes that.
@jaw-sh Does the `stickied_at` column get set to `NULL` when a thread is unstickied? Otherwise, that should be fixed as well.

**Comment by GarbageHamburger** [comment]
https://github.com/infinity-next/infinity-next/blob/master/app/Post.php#L1624
Seems like it does get set to `NULL`. Sending a PR.
